### ISSUE TITLE
Can't authorize under existing user

### ISSUE THREAD

**Issue by evgeniy-kharchenko** [vaulttec/sonar-auth-oidc#41]
Hi Everybody,
I've Keycloack instanse 9.0.3 version and SonarQube of 7.9.3.LTS.
This is configuration on Keycloack side 
![image](https://user-images.githubusercontent.com/54746592/81811572-84111380-952d-11ea-96a7-201733c55464.png)
![image](https://user-images.githubusercontent.com/54746592/81811626-9a1ed400-952d-11ea-9f3c-7cc0e5ddd531.png)
This is configuration on Sonar Qube side
![image](https://user-images.githubusercontent.com/54746592/81811752-d0f4ea00-952d-11ea-927b-7b9d4d2b55c6.png)
![image](https://user-images.githubusercontent.com/54746592/81811825-eb2ec800-952d-11ea-863d-558befdccba2.png)
![image](https://user-images.githubusercontent.com/54746592/81811854-f681f380-952d-11ea-99f7-2060640939f3.png)
![image](https://user-images.githubusercontent.com/54746592/81811887-04d00f80-952e-11ea-96f6-66ad1b49a29e.png)
When I trying to authorize under my account i face:
![image](https://user-images.githubusercontent.com/54746592/81812684-27165d00-952f-11ea-9d6e-70609f19164d.png)
It seems that the system thinks that I'am a new user, but I want to login under existing.
How can I resolve the issue?

Thanks in advance!

**Comment by tjuerge** [comment]
Which version of the pugin you are using?

Version 2+ of this plugin is built for SonarQube version 8+ which does not support authenticating with external identity providers for existing users (Login generation strategy: Preferred username) any more. SonarSource disabled the corresponding API implementation. Please check the corresponding [release notes](https://github.com/vaulttec/sonar-auth-oidc/releases/tag/v2.0.0) for further details.

So for SonarQube version 7.x you could stay with version 1.x of this plugin. But after upgrading to SQ v8+ this plugin version will not work anymore.

**Comment by evgeniy-kharchenko** [comment]
Hi Torsten Juergeleit,
Thank you for your answer.

Firstly, I've downloaded "sonar-auth-oidc-plugin-2.0.0.jar" version of plugin.

A few minutes ago i've installed sonar-auth-oidc-plugin-1.1.0.jar.
And now when I trying to login I see:
![image](https://user-images.githubusercontent.com/54746592/81845272-06fb9380-9559-11ea-9d6b-99ab4579e002.png)

Just to clarify (sorry for my misunderstanding): Does the plugin sonar-auth-oidc-plugin-1.1.0.jar  support the sign in under existing user?

**Comment by tjuerge** [comment]
I didn't read your detailed description thoroughly and jumped to the wrong conclusion. Sorry about that.

SonarQube's `OAuth2IdentityProvider` API (which is used by this plugin) is not able to associate existing (internally managed) user identities with identities managed by an external identity provider adequately. The plugin's login generation strategy option (used to generate the corresponding SQ username) is only a kludge (which is totally useless since the API change [SONAR-12475](https://jira.sonarsource.com/browse/SONAR-12475) introduced in SQ 8).

So, no, you can't safely link existing user accounts with the user accounts created by the plugin's implementation of `OAuth2IdentityProvider`. To omit SQ's account association dialog (as shown in one of your screenshots) the plugin would need an login generation strategy which adheres to the exact username creation strategy of your existing accounts. SQ can only best-guess by the email address which accounts are related.

And starting with SQ 8+ [pre-creating user accounts with usernames which are supported by the plugin's login generation strategy is not possible any more](https://community.sonarsource.com/t/how-to-pre-create-users-who-will-authenticate-via-an-identity-provider-with-sq-8/24207).
