### ISSUE TITLE
OpenID Connect create a duplicate entry in backend for same user email when integrated with AUTH0

### ISSUE THREAD

**Issue by yogesh206145** [vaulttec/sonar-auth-oidc#49]
Hi Team,  
We are trying to migrate SSO from Microsoft Azure AD to Auth0 with OpenID connect and able to login .I am sending you all the details and challenges:
   When a user is already login with Microsoft Azure AD ,All the groups are in sync and  Sonarqube Tokens are also associated with user. Now the same   user try to login via OpenID Connect with Auth0, He is getting the warning message <Screen User Information when login via OIDC >. When the user Click on Continue,  User is able to login  but a duplicate user is created with some random identity having Same email <Screen User Information when login via OIDC >.Group sync happen  properly  for the user but existing sonarqube token is not migrated/mapped to user. I am sending you complete setup details <Screen OPEN Connect Configuration Screens>, please provide support on urgent basis .
  1.Duplicate should not be created when login with same user email irrespective of Azure AD or AUTH0 
2. All the existing groups or sonarqube token should be mapped correctly  
3.Existing user token should work in all CICD pipeline.

NOTE: I am using SonarQube 7.9.4
[OPEN Connect Configuration Screens.docx](https://github.com/vaulttec/sonar-auth-oidc/files/5401089/OPEN.Connect.Configuration.Screens.docx)
[User Information when login via OIDC.docx](https://github.com/vaulttec/sonar-auth-oidc/files/5401092/User.Information.when.login.via.OIDC.docx)

**Comment by tjuerge** [comment]
Which version of the plugin are you using?

Beginning with v2.0.0 the plugin is implemented in compliance with a breaking API change introduced in  SonarQube 8 (auto generating a new user account on first login with a new SSO provider #31). This is mentioned in the [release notes](https://github.com/vaulttec/sonar-auth-oidc/tree/v2.0.0).

For keeping the old behavior you have to stay on SQ 7.x and plugin v1.1.0.

**Comment by yogesh206145** [comment]
@tjuerge : Thanks for your response I am using SQ 7.x but with plugin V2.0.0. I will test with v1.1.0 and get back to you if I have any issue. Thank you very much :)

**Comment by tjuerge** [comment]
Please keep in mind, that switching the OIDC provider introduces a different provider-specific sub value (Subject Identifier) in the [OIDC id token](https://connect2id.com/learn/openid-connect). This sub value is given to SQ as `providerLogin`in it's [UserIdentity](http://javadocs.sonarsource.org/7.8/apidocs/org/sonar/api/server/authentication/UserIdentity.html#getProviderLogin()) object during authentication.

Meaning, despite of the same login (preferred username) and email SQ will not re-use existing user accounts from different authentication providers. Due to the different subject identifier new accounts will be created. But the same login (user id) and email can't be used for different accounts in SQ. Therefore a modified user id is created by SQ and the email is removed from the existing account.

At the end of the day you can't re-use the existing Azure-created SQ accounts with Auth0 without modifying the subject identifier in SQ's internal database by yourself. Please check with SQ how to handle this.

And beginning with SQ 8 the login (preferred username) can't be specified anymore. This is always generated by SQ during first login. Please check with SQ for this as well. Here's a [similar SQ community forum entry](https://community.sonarsource.com/t/how-to-pre-create-users-who-will-authenticate-via-an-identity-provider-with-sq-8/24207).

**Comment by yogesh206145** [comment]
@tjuerge : I have tested SQ 7.9X with plugin v1.1.0 and it seems I got expected result as user is able to login , group synced, token synced. However a random no still generated (Please check attachment). Some users getting a complain " unauthorized" and in backend I got a log error " Fail to callback authentication with 'oidc" as the user already exist. I have selected login generation strategy as "Email".

Can you please help me on this ?How to fix authentication error.
[Behaviour of SQ 7.9docx.docx](https://github.com/vaulttec/sonar-auth-oidc/files/5428690/Behaviour.of.SQ.7.9docx.docx)

**Comment by tjuerge** [comment]
As explained in my [previous comment](https://github.com/vaulttec/sonar-auth-oidc/issues/49#issuecomment-713748136) SQ's API doesn't allow to re-use the same email or username / userid for different authentication providers. If switching authentication providers for the same users you must delete the existing SQ accounts (associated with the previous authentication provider) and recreate them with the new authentication provider. You'll end up with randomized emails or usernames / userids. This is how SQ deals with existing accounts using the same emails or usernames / userids.

The only workaround is to modify the provider id of the existing accounts in SQ's database. Please check with SQ how to handle this.

Sorry, there's nothing this plugin can help with. This is a SQ-only thing.

**Comment by tjuerge** [comment]
I forwarded your issue to SQ in [SONAR-13930 Allow migration of authentication system](https://jira.sonarsource.com/browse/SONAR-13930).

**Comment by tjuerge** [comment]
Btw. the reasoning behind the change [SONAR-12475 Drop login generation strategy when using an Identity Provider](https://jira.sonarsource.com/browse/SONAR-12475) introduced in SQ 8.1 can be found in the SQ community forum entry [User login not deterministic after update to 8.1 with SAML authentication](https://community.sonarsource.com/t/user-login-not-deterministic-after-update-to-8-1-with-saml-authentication/31660/2):

> The reason why logins are now automatically generated is that in case multiple ALMs are used, we want to prevent any situation where 2 identical logins could be generated.
