### ISSUE TITLE
Pluggin not starting properly

### ISSUE THREAD

**Issue by jakkaras** [vaulttec/sonar-auth-oidc#70]
Hi,

After last update of Sonarqube, and Pluggin, the pluggin does not work.

In sonarqube marketplace the pluggin is showed as installed. 
The only line of log which is connected to sonar-auth-oidc is the following:
INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter [org.vaulttec.sonarqube.auth.oidc.AutoLoginFilter@4bbb7664](mailto:org.vaulttec.sonarqube.auth.oidc.AutoLoginFilter@4bbb7664) [pattern=UrlPattern{inclusions=[/sessions/new], exclusions=[]}]

After downgrading the pluggin to previous version on the new Sonarqube version, everything is working fine.

Old version of pluggin: 1.1.0
New version of pluggin: 2.1.1
New Sonarqube Version: 9.9.0

As I am unable to find any error messages, or anything elese which migh guide me what is wrong, I will be gratefull for your help.

BR
Jakub Karaś

**Comment by duckfly-tw** [comment]
My sonarqube version is 9.9.1, and no matter which version of plugin (2.1.1 or 1.1.0) , it doesn't work for me.

My symptom is:

The first one OIDC user can auto register and sign-in,  but the second one just can't success, and sonarqube will show the message like "you need to be authorized"., that means only one OIDC user can register and login.

But if I delete the first one (also as the only one) OIDC user, other OIDC user become allowed to register and sign-in, but just only one is allowed, that's weired.

**Comment by tjuerge** [comment]
> My sonarqube version is 9.9.1, and no matter which version of plugin (2.1.1 or **1.1.0**) , it doesn't work for me.

Plugin version 1.x is intented for Sonarqube version prior to 8.0 (due to SQ API changes introduced in version 8.0). This is explained in the [release notes of plugin v2.0](https://github.com/vaulttec/sonar-auth-oidc/releases/tag/v2.0.0)  or #31.

Plugin v2.0 (or newer) is intended for Sonarqube 8.0 (or newer).

**Comment by duckfly-tw** [comment]
> Plugin version 1.x is intented for Sonarqube version prior to 8.0 (due to SQ API changes introduced in version 8.0). This is explained in the [release notes of plugin v2.0](https://github.com/vaulttec/sonar-auth-oidc/releases/tag/v2.0.0) or #31.
> 
> Plugin v2.0 (or newer) is intended for Sonarqube 8.0 (or newer).

thanks for your reply, but in my newly installation of sonarqube 9.9.1, oidc pluging of version 2.1.1 allow only one to register, and @jakkaras  said it is working with version 1.1.0, that's why I tried it, but still not work.

I'll get the debug log posted on in a near day, thanks.

**Comment by duckfly-tw** [comment]
Thanks for your hint, from debug log I found the reason, OP always give blank email for everyone if I don't ask for that,
and oidc plugin use email as a key, so I apply for personal email to OP and I already fix it.

`2023.09.05 05:51:09 DEBUG web[AYpj0Uek6x6ZVcKLAAEG][o.v.s.a.o.OidcIdentityProvider] Authenticating user 'user01' with groups []
2023.09.05 05:51:09 DEBUG web[AYpj0Uek6x6ZVcKLAAEG][auth.event] login failure [cause|Email '' is already used][method|OAUTH2][provider|EXTERNAL|OpenID Connect][IP|10.1.1.1|1.2.3.4][login|user01]`

BTW, I set plugin option <Login generation strategy> as "custom claim" and <Login strategy custom claim> as "sub",
why doesn't plugin use "sub" as a key instead of "email"?
![image](https://github.com/vaulttec/sonar-auth-oidc/assets/11530932/f01a1ee7-2498-4d77-968f-62fc4ce9d617)

**Comment by tjuerge** [comment]
I'm glad you solved the issue with your identity povider.

> BTW, I set plugin option "Login generation strategy" as "custom claim" and "Login strategy custom claim" as "sub",

This is the same as using the built-in [login strategy "Same as OpenID Connect login"](https://github.com/vaulttec/sonar-auth-oidc/blob/master/src/main/java/org/vaulttec/sonarqube/auth/oidc/UserIdentityFactory.java#L61)

> why doesn't plugin use "sub" as a key instead of "email"?

Sub is already [used as (optional) unique provider ID](https://github.com/vaulttec/sonar-auth-oidc/blob/master/src/main/java/org/vaulttec/sonarqube/auth/oidc/UserIdentityFactory.java#L44) for [SQs `UserIdentity`](https://github.com/SonarSource/sonar-plugin-api/blob/f456f3c596bd8b6bb0753e5ed25ecf91d52bd085/plugin-api/src/main/java/org/sonar/api/server/authentication/UserIdentity.java#L68).

> Or unique email is necessary for OIDC new login user?

In SQs `UserIdentity` the email is optional - but if non-null then it must unique across all identity providers. This is specified in [SQs API contract](https://github.com/SonarSource/sonar-plugin-api/blob/f456f3c596bd8b6bb0753e5ed25ecf91d52bd085/plugin-api/src/main/java/org/sonar/api/server/authentication/UserIdentity.java#L105).
